In [ ]:
# Copyright © 2022 Indonesia AI. All Rights Reserved.
# contact@aiforindonesia.org

### Membuat Numpy Array

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# Python List

a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

type(a), type(b)

(list, list)

In [ ]:
print(a + b)

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
print(a * b)

TypeError: ignored

In [ ]:
arrayA = np.array(a)
arrayB = np.array(b)

type(arrayA), type(arrayB)

(numpy.ndarray, numpy.ndarray)

In [ ]:
print(arrayA + arrayB)
print(arrayA / arrayB)

[ 6  8 10 12]
[0.2        0.33333333 0.42857143 0.5       ]


In [ ]:
print(arrayA * 10) # broadcasting

[10 20 30 40]


In [ ]:
y_pred = np.array([1, 0, 0, 1, 1, 0, 1, 1])
labels = np.array([0, 1, 0, 1, 1, 0, 1, 1])

mse = (1/len(labels)) * np.sum(np.square(y_pred - labels))
print(mse)

0.25


### Membuat Numpy Array 0 Dimensi (0D)

In [ ]:
arr = np.array(42)

print(arr)

42


### Membuat Numpy Array 1 Dimensi (1D)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


### Membuat Numpy Array 2 Dimensi (2D)

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


### Membuat Numpy Array 3 Dimensi (3D)

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], 
                [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### Membuat Numpy Array 0s dan 1s

In [ ]:
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [ ]:
arr = np.zeros((5, 2))
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
arr = np.ones((7, 7))
print(arr)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
arr = np.ones((3, 4, 2))
print(arr)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


### Menghapus Array

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr = np.delete(arr, 1, axis=0)
print(arr)

[[1 2 3]
 [7 8 9]]


In [ ]:
del arr

### Mengakses Elemen Pada Numpy Array 1D

In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


### Mengakses Elemen Pada Numpy Array 2D

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[1, 4])

10


### Mengakses Elemen Pada Numpy Array 2D

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], 
                [[1, 2, 3], [4, 5, 6]]])

print(arr[0, 1, 2])

6


### Mengakses Numpy Array dengan indeks negatif

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[1, -1])

10


### Mengakses Elemen Sekaligus Pada Numpy Array

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


### Mengecek Tipe Data Pada Numpy Array

In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


### Mendefinisikan Tipe Data Pada Numpy Array

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
arr = np.array([1, 2, 3, 4], dtype='I')

print(arr)
print(arr.dtype)

[1 2 3 4]
uint32


In [ ]:
arr = np.array([1, 2, 3, 4], dtype=np.int16)

print(arr)
print(arr.dtype)

[1 2 3 4]
int16


### Mengubah Tipe Data Pada Numpy Array

In [ ]:
arr = np.array([1.1, 2.1, 3.1])
arr = arr.astype('i')

print(arr)
print(arr.dtype)

[1 2 3]
int32


### Fungsi Arange

In [ ]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
arr = np.arange(10, 20)
print(arr)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
arr = np.arange(10, 20, 2) # arguments: start, stop, step
print(arr)

[10 12 14 16 18]


In [ ]:
arr = np.arange(-1, 1, 0.1)
print(arr)

[-1.00000000e+00 -9.00000000e-01 -8.00000000e-01 -7.00000000e-01
 -6.00000000e-01 -5.00000000e-01 -4.00000000e-01 -3.00000000e-01
 -2.00000000e-01 -1.00000000e-01 -2.22044605e-16  1.00000000e-01
  2.00000000e-01  3.00000000e-01  4.00000000e-01  5.00000000e-01
  6.00000000e-01  7.00000000e-01  8.00000000e-01  9.00000000e-01]


---