In [1]:
# Copyright © 2022 Indonesia AI. All Rights Reserved.
# contact@aiforindonesia.org

### Mendapatkan shape dari Array

In [2]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [3]:
print(arr.size)

8


In [4]:
print(arr.ndim)

2


### Menggunakan ndmin untuk mendefinisikan dimensi

In [5]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr.shape)

(1, 1, 1, 1, 4)


### Reshape dari 1D ke 2D

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr = arr.reshape(4, 3)

print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Reshape dari 1D ke 3D

In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr = arr.reshape(2, 3, 2)

print(arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### Menggunakan -1 pada proses reshaping

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr= arr.reshape(2, 2, -1)

print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Melakukan flattening pada Array

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr= arr.reshape(-1)

print(arr)

[1 2 3 4 5 6]


In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr= arr.flatten()

print(arr)

[1 2 3 4 5 6]


### Melakukan duplikasi pada Array menggunakan copy()

In [11]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr, x)

[42  2  3  4  5] [1 2 3 4 5]


### Melakukan duplikasi pada Array menggunakan view()

In [12]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr, x)

[42  2  3  4  5] [42  2  3  4  5]


---