In [ ]:
# Copyright © 2022 Indonesia AI. All Rights Reserved.
# contact@aiforindonesia.org

### Iterasi pada Numpy Arrray 1D

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
    print(x)

1
2
3


### Iterasi pada Numpy Arrray 2D

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


### Iterasi pada Numpy Arrray 3D

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], 
                [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


### Iterasi dengan nditer()

In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


### Iterasi dengan ndenumerate() pada Array 1D

In [ ]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


### Iterasi dengan ndenumerate() pada Array 2D

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


### Join terhadap 2 Array 1D

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


### Join terhadap 2 Array 2D

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


### Stack terhadap 2 Array 1D

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


### Stack terhadap 2 Array 1D menggunakan hstack()

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


### Stack terhadap 2 Array 1D menggunakan vstack()

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


### Split terhadap 1 Array 1D

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr = np.array_split(arr, 4)

print(arr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


### Split terhadap 1 Array 2D

In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6], 
                [7, 8], [9, 10], [11, 12]])
arr = np.array_split(arr, 3)

print(arr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6], 
                [7, 8], [9, 10], [11, 12]])
arr = np.array_split(arr, 3, axis=1)

print(arr)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int64)]


### Search pada Array 1D

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr**2 == 4)

print(x)

(array([1]),)


### Sort pada Array 1D

In [ ]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [ ]:
arr = np.array(['pisang', 'melon', 'apel'])

print(np.sort(arr))

['apel' 'melon' 'pisang']


### Sort pada Array 2D

In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


---