In [ ]:
# Copyright © 2022 Indonesia AI. All Rights Reserved.
# contact@aiforindonesia.org

### Mendapatkan nilai integer secara random

In [ ]:
from numpy import random

x = random.randint(100)

print(x)

22


### Mendapatkan nilai float secara random

In [ ]:
x = random.rand()

print(x)

0.33553885090365543


### Membuat Array 1D dengan nilai integer secara Random

In [ ]:
x = random.randint(100, size=(5))

print(x)

[ 5 58 63 35 75]


### Membuat Array 2D dengan nilai integer secara Random

In [ ]:
x = random.randint(100, size=(3, 5))

print(x)

[[31 79 31 56 18]
 [80 21 50 31 18]
 [63 18 59 28  3]]


### Membuat Array 1D dengan nilai float secara Random

In [ ]:
x = random.rand(5)

print(x)

[0.33158433 0.40869198 0.7893277  0.70715339 0.36104075]


### Membuat Array 2D dengan nilai float secara Random

In [ ]:
x = random.rand(3, 5)

print(x)

[[0.17154852 0.24903471 0.31508807 0.09304131 0.9576493 ]
 [0.5122721  0.84050068 0.24508325 0.00696401 0.79633127]
 [0.38470687 0.47702144 0.86665335 0.01258899 0.91271168]]


### Membuat nilai integer random dari Array 1D

In [ ]:
x = random.choice([3, 5, 7, 9])

print(x)

3


### Mengacak nilai yang ada pada Array 1D

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
random.shuffle(arr)

print(arr)

[5 1 4 3 2]


---